data_entry/urls.py
from django.urls import path
from .views import *

app_name = "data_entry"
urlpatterns = [
    path('main/', home_view, name="main"),
    path('entryportal/', portal_view, name="portal"),
    path('portal/', entry_view, name="entry"),
    path('camera/', camera_view, name="camera"),
    path('view/', view_entry, name="view"),
    path('delete/<int:id>/', delete_entry, name="delete"),
    path('logout/', logout_request, name='logout'),
    path('update/<int:id>/', update_entry, name="update"),
    path('csv/', export_excel, name="csv")
]

form/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url('', include("pwa.urls")),
                  path('', include("login.urls")),
                  path('data/', include("data_entry.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
    path('home/', main_view, name="index"),
    path('', login_vew, name="login"),
    path('logout/', logout_request, name='logout')
]

templates/view_entry/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<script src="{% static 'js/1.js' %}"></script>
	<link rel="stylesheet" href="{% static 'CSS/1.css' %}">
	<link rel="icon" href="{% static 'LOGO/img2.png' %}" type="image/x-icon">
	<title>Data Entry Portal</title>
</head>

<body class="animated_bg">
	<nav class="navbar nav nav-pills navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
		<div class="container-fluid">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar"> <span class="navbar-toggler-icon"></span> </button>
			<a class="navbar-brand mr-auto" href="{% url 'data_entry:main' %}"><img src="{% static 'Image/img.jpg' %}" height="40" width="41"></a>
			<div class="collapse navbar-collapse" id="Navbar">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:main' %}">Home</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:view' %}">View Entry</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:entry' %}">Data Entry</a></li>
					<li class="nav-item"><a class="nav-link active" href="#">Update Entry</a></li>
				</ul>
			</div> <span class="navbar-text" id="logout">
				<a href="{% url 'login:logout' %}" ><span class="fa fa-sign-out"></span> Logout</a>
			</span>
		</div>
	</nav>
	<div class="container">
		<div class="row">
			<ol class="col-12 breadcrumb crumb">
				<li class="breadcrumb-item"><a href="#">Home</a></li>
				<li class="breadcrumb-item"><a href="#">View Entry</a></li>
				<li class="breadcrumb-item active">Data Entry</li>
			</ol>
		</div>
	</div>
	<br>
	<form method="post" action="" enctype="multipart/form-data"> {% csrf_token %}
		<div class="container-lg">
			<div class="row row-content">
				<div class="col-12 offset-md-4 col-md-4">
					<h2>Registration Portal</h2> </div>
			</div>
			<table>
				<div class="row row-conten"> {{form.as_table}} </div>
			</table>
			<div class="row row-content">
				<div class="col-6 offset-md-1 col-md-7">
					<div class="col-1 offset-md-11 col-md-">
						<input type="submit" class="btn btn-btn btn-primary" value="Update"> </div>
				</div>
				<div class="col-5 offset-md-1 col-md-1">
					<div class="col-5 col-md-">
						<input type="reset" class="btn btn-btn btn-primary"> </div>
				</div>
			</div>
		</div>
	</form>
</body>
<footer class="container-fluid bg-dark mt-5">
	<div class="card-lg bg-dark w-150">
		<div class="card-body">
			<!-- Copyright -->
			<div class="footer-copyright text-center" id="footer">© 2020 Copyright: <a href="https://ssdndeepu.com.com/"> SSDNDEEPU</a>
				<br>All Rights Reserved
				<br>
				<p> By using our site, you acknowledge that you have read and understand our <a href="TUS.html" target="_blank">Terms of Service.</a> </p>
			</div>
			<!-- Copyright -->
		</div>
	</div>
</footer>
<script type="text/javascript">
document.getElementById("Darbar").value = {
	{
		single.Darbar
	}
};
</script>
</body>

</html>

templates/view_entry/view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'CSS/4.css' %}">
	<link rel="icon" href="{% static 'LOGO/img2.png' %}" type="image/x-icon">
	<title>Data Entry Portal</title>
</head>

<body>
	<nav class="navbar nav nav-pills navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
		<div class="container-fluid ">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar"> <span class="navbar-toggler-icon"></span> </button>
			<a class="navbar-brand mr-auto" href="{% url 'data_entry:main' %}"><img src="{% static 'Image/img.jpg' %}" height="40" width="41"></a>
			<div class="collapse navbar-collapse" id="Navbar">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:main' %}">Home</a></li>
					<li class="nav-item"><a class="nav-link  active" href="#">View Entry</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:portal' %}">Data Entry</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:csv' %}">Export to Excel</a></li>
				</ul>
				<form class="form-inline mr-3" method="get">
					<input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div> <span class="navbar-text" id="logout">
				<a href="{% url 'login:logout' %}" ><span class="fa fa-sign-out"></span> Logout</a>
			</span>
		</div>
	</nav>
	<div class="container-lg">
		<div class="row row-content">
			<div class="col-12 offset-md-4 col-md-4">
				<h2 id="Entry">View Portal</h2> </div>
		</div> {% for post in posts %}
		{%  if post.flag %}
		<div class="row disp1">
			<div class="col-12 offset-md-1 col-md-10">
				<div class="card bg-light text-left" style="max-width:90rem;">
					<div class="row"> {% if post.image %}
						<div class="col-12 col-md-3 fix ml-1"> <img class="card-img fix" src="{{post.image.url}}" alt="{{post.full_Name}}"> </div> {% endif %}
						<div class="col-12 col-md-8 fix ml-0">
							<h4 class="card-title">Name: {{post.full_Name}}</h4>
							<h6 class="card-text">Father's name: {{post.father_Name}}</h6>
							<h6 class="card-text">Gender: {{post.Gender}}</h6>
							<h6>Phone No: {{post.phone}}</h6>
							<h6>Darbar: {{post.Darbar}}</h6>
							<h6>Address:{{post.Address}}</h6> </div>
					</div>
					<div class="row mt-0 size">
						<div class="col-12 offset-md-8 col-md-2"> <a href="{% url 'data_entry:update' post.id %}" class="btn btn-primary btn-sm">View Entry</a> </div>
						<div class="col-12 col-md-2 mb-2"> <a href="{% url 'data_entry:delete' post.id %}" class="btn btn-danger btn-sm">Delete Entry</a> </div>
					</div>
					<div class="card-footer"> <small class="text-muted">Last Updated {{post.publishing_date}} by {{post.user}}</small> </div>
				</div>
			</div>

		</div>
		<div class="row row-content disp">
			<div class="col-12 offset-md-4 col-md-4">
				<div class="card">
					<div class="col-12 col-md-3 fix ml-1">  </div>
					<div class="card-body">
						<p class="card-text">Father's name: {{post.father_Name}}
							<br> Phone No:{{post.phone}}
							<br> Darbar: {{post.Darbar}}
							<br> Address: {{post.Address}}</p>
					</div>
					<div class="row mt-0">
						<div class="ml-2 col-6"> <a href="{% url 'data_entry:update' post.id %}" class="btn btn-primary btn-sm">View Entry</a> </div>
						<div class="col-5 col-md-2 mb-1"> <a href="{% url 'data_entry:delete' post.id %}" class="btn btn-danger btn-sm">Delete Entry</a> </div>
					</div>
					<div class="card-footer"> <small class="text-muted">Last Updated {{post.publishing_date}} by {{post.user}}</small> </div>
				</div>
			</div>
			{% endif %}
		</div>
		<br> {% endfor %}
		<div class="row row-content">
			<div class="col-12 offset-md-5 col-md-4">
				<div class="pagination"> <span class="step-links">
					{% if posts.has_previous %}
            			<a href="?page={{ posts.previous_page_number }}  {% if request.GET.q %}&q=={{request.GET.q}}{% endif %} "><i class="fa fa-lg fa-arrow-left" aria-hidden="true"></i></a>
        			{% endif %}

        			<span class="current">
            			Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        			</span> {% if posts.has_next %} <a href="?page={{ posts.next_page_number }}  {% if request.GET.q %}&q=={{request.GET.q}}{% endif %} "><i class="fa fa-lg fa-arrow-right" aria-hidden="true"></i></a> {% endif %} </span>
				</div>
			</div>
		</div>
	</div>
	<footer class="container-fluid bg-dark mt-5">
		<div class="card-lg bg-dark w-100">
			<div class="card-body">
				<!-- Copyright -->
				<div class="footer-copyright text-center" id="footer">© 2020 Copyright: <a href="https://ssdndeepu.com.com/"> SSDNDEEPU</a>
					<br>All Rights Reserved
					<br>
					<p> By using our site, you acknowledge that you have read and understand our <a href="TUS.html" target="_blank">Terms of Service.</a> </p>
				</div>
				<!-- Copyright -->
			</div>
		</div>
	</footer>
</body>

</html>