form/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url('', include("pwa.urls")),
                  path('', include("login.urls")),
                  path('data/', include("data_entry.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
    path('home/', main_view, name="index"),
    path('', login_vew, name="login"),
    path('logout/', logout_request, name='logout')
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect


def main_view(request):
    return render(request, "login/login.html")


def login_vew(request):
    email = request.POST.get('email')
    password = request.POST.get('password')
    user = authenticate(request, email=email, password=password)
    if user is not None:
        login(request, user)
        return redirect('data_entry:main')
    else:
        return render(request, "login/login.html")


@login_required(login_url='login:index')
def logout_request(request):
    logout(request)
    return redirect("login:index")

templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'CSS/2.css' %}">
	<link rel="icon" href="{% static 'LOGO/img2.png' %}" type="image/x-icon">
	<title>Login Portal</title>
</head>

<body class="animated_bg">
	<form method="POST" action="{% url 'login:login' %}"> {% csrf_token %}
		<div class="container-lg">
			<div class="row row-content">
				<div class="col-12 offset-md-3 col-md-6">
					<h3 id="entry">Welcome</h3>
					<br> </div>
				<div class="col-12 offset-4 offset-md-5 col-md-7"> <img src="{% static 'Image/img.jpg' %}" height="60" width="61"></a>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-12"> {% if form.non_field_errors %} {% for error in form.non_field_errors %}
					<p class="text-danger">*<b>{{ error }}</b></p> {% endfor %} {% endif %}
					<label for="e-mail" class="col-md-2 col-form-label">Email:</label>
					<div class="col-md-12">
						<input type="text" placeholder="E-mail" class="form-control" id="e-mail" name="email">
					</div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-12">
					<label for="password" class="col-md-4 col-form-label">Password:</label>
					<div class="col-md-12">
						<input type="password" placeholder="Password" class="form-control" id="password" required name="password"> </div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-12">
					<div class="col-md-12">
						<input type="checkbox" id="remember" name="remember">
						<label for="remember" class="col-form-label">Remember Me</label>
					</div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 offset-md-2 col-md-8">
					<div class="col-12 col-md-12">
						<input type="submit" class="btn btn-block btn-primary" value="Login"> </div>
				</div>
			</div>
			<div class="row row-content"> </div>
	</form>
</body>

</html>

templates/login/register.html
{% extends 'base.html' %} {% load static %} {% block content%}
<div class="container">
	<h3>Login Form</h3>
	<form method="post"> {% csrf_token %} {{form.as_p}}
		<input type="submit" value="Register"> </form>
</div> {% endblock %}