data_entry/urls.py
from django.urls import path
from .views import *

app_name = "data_entry"
urlpatterns = [
    path('main/', home_view, name="main"),
    path('entryportal/', portal_view, name="portal"),
    path('portal/', entry_view, name="entry"),
    path('camera/', camera_view, name="camera"),
    path('view/', view_entry, name="view"),
    path('delete/<int:id>/', delete_entry, name="delete"),
    path('logout/', logout_request, name='logout'),
    path('update/<int:id>/', update_entry, name="update"),
    path('csv/', export_excel, name="csv")
]

form/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url('', include("pwa.urls")),
                  path('', include("login.urls")),
                  path('data/', include("data_entry.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
    path('home/', main_view, name="index"),
    path('', login_vew, name="login"),
    path('logout/', logout_request, name='logout')
]

data_entry/models.py
from django.conf import settings
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Darbar(models.Model):
    darbar_name = models.CharField(max_length=500)
    darbar_city = models.CharField(max_length=500)


class Post(models.Model):
    Occupation_CHOICES = (
        ('Healthcare and medicine', 'Healthcare and medicine'),
        ('Arts and entertainment', 'Arts and entertainment'),
        ('Business', 'Business'),
        ('Industrial and manufacturing', 'Industrial and manufacturing'),
        ('Engineer', 'Engineer'),
        ('Law enforcement and armed forces', 'Law enforcement and armed forces'),
        ('Science and technology', 'Science and technology'),
        ('Transport', 'Transport'),
        ('Service(Labour)', 'Service(Labour)')
    )
    Darbar_Choices = (('Shri Anand Niwas Satsang, Memnagar', 'Shri Anand Niwas Satsang, Memnagar',),
                      ('Shri Anand Niwas Satsang, Maninagar', 'Shri Anand Niwas Satsang, Maninagar'),
                      ('Shri Anand Niwas Satsang, SardarNagar', 'Shri Anand Niwas Satsang, Sardarnagar'),
                      ('Shri Anand Niwas Satsang, Sahjpur', 'Shri Anand Niwas Satsang, Sahjpur'))
    Blood_Choices = (
        ('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('Not Known', 'Not Known'))
    GENDER_CHOICES = (('Male', 'Male'), ('Female', 'Female'))
    full_Name = models.CharField(max_length=300)
    spouse_Name = models.CharField(max_length=300, blank=True, null=True)
    father_Name = models.CharField(max_length=300)
    mother_Name = models.CharField(max_length=300)
    Occupation = models.CharField(max_length=500, null=True, choices=Occupation_CHOICES)
    Gender = models.CharField(null=True, max_length=100)
    blood_Group = models.CharField(max_length=100, null=True, choices=Blood_Choices)
    birth_date = models.DateField()
    phone = PhoneNumberField(blank=True)
    Darbar = models.CharField(max_length=500, default='Please Select Darbar', null=True, choices=Darbar_Choices)
    Address = models.CharField(max_length=500, default="Please Enter Address")
    Pincode = models.CharField(max_length=6, default="Please Enter Pincode")
    image = models.ImageField(upload_to="images/")
    publishing_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False)
    flag = models.BooleanField(default=True)
    city = models.CharField(max_length=200, default=None)

    class Meta:
        db_table = "post"
        ordering = ['-id']

    def __str__(self):
        return self.full_Name

data_entry/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['full_Name', 'spouse_Name', 'father_Name', 'mother_Name', 'Occupation', 'Gender', 'blood_Group', 'birth_date', 'phone', 'Darbar','Address','Pincode','image']

data_entry/views.py
import csv
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from users.models import Account
from .forms import PostForm
from .models import Post, Darbar


@login_required
def home_view(request):
    value = Post.objects.count()
    value_male = Post.objects.filter(Gender='Male').count()
    value_female = Post.objects.filter(Gender='Female').count()
    context = {'value': value, 'value_male': value_male, 'value_female': value_female}
    return render(request, "main/home.html", context)


@login_required(login_url='login:index')
def portal_view(request):
    users = Account.objects.filter(id=request.user.id).values('city')
    city = ''
    for user in users:
        city = str(user['city'])
    context = {'darbars': list(Darbar.objects.filter(darbar_city=city).values('darbar_name'))}
    return render(request, 'data_entry/dataentry.html', context)


@login_required(login_url='login:index')
def entry_view(request):
    if request.method == 'POST':
        post = Post()
        post.full_Name = request.POST['full_Name']
        if request.POST['spouse_Name']:
            post.spouse_Name = request.POST['spouse_Name']
        else:
            post.spouse_Name = ""
        post.father_Name = request.POST['father_Name']
        post.mother_Name = request.POST['mother_Name']
        post.Occupation = request.POST['Occupation']
        post.Gender = request.POST['Gender']
        post.blood_Group = request.POST['blood_Group']
        post.birth_date = request.POST['birth_date']
        post.phone = request.POST['phone']
        post.Darbar = request.POST['Darbar']
        post.Address = request.POST['Address']
        post.Pincode = request.POST['Pincode']
        post.image = request.FILES['myfile']
        post.user = request.user
        post.city = request.user.city
        post.save()
        # for full_Name, father_Name, mother_Name in Post.objects.values_list('full_Name','father_Name', 'mother_Name', flat=False).distinct():
        #    Post.objects.filter(
        #        pk__in=Post.objects.filter(full_Name=full_Name, father_Name=father_Name, mother_Name=mother_Name).values_list('id', flat=False)[1:]).delete()
        return redirect("data_entry:main")
    else:
        return render(request, 'data_entry/dataentry.html')


@login_required(login_url='login:index')
def camera_view(request):
    return render(request, "data_entry/winner.html")


@login_required(login_url='login:index')
def view_entry(request):
    users = Account.objects.filter(id=request.user.id).values('city')
    city = ''
    for user in users:
        city = str(user['city'])
    post_list = Post.objects.filter(city=city)
    paginator = Paginator(post_list, 3)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    context = {
        'posts': post_list
    }
    return render(request, 'view_entry/view.html', context)


@login_required(login_url='login:index')
def delete_entry(request, id):
    post = get_object_or_404(Post, id=id)
    post.flag = 0
    post.save()
    return redirect('data_entry:view')


@login_required(login_url='login:index')
def logout_request(request):
    logout(request)
    return redirect("index")


@login_required(login_url='login:index')
def update_entry(request, id):
    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post.save()
        return redirect('data_entry:view')
    context = {
        'form': form
    }
    return render(request, 'view_entry/update.html', context)


@login_required(login_url='login:index')
def export_excel(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'

    writer = csv.writer(response)
    writer.writerow(['full_Name', 'spouse_Name', 'father_Name', 'mother_Name', 'Occupation', 'Gender', 'blood_Group',
                     'birth_date', 'phone', 'Darbar', 'Address', 'Pincode'])

    users = Post.objects.all().values_list('full_Name', 'spouse_Name', 'father_Name', 'mother_Name', 'Occupation',
                                           'Gender', 'blood_Group',
                                           'birth_date', 'phone', 'Darbar', 'Address', 'Pincode')
    for user in users:
        writer.writerow(user)

    return response

templates/data_entry/dataentry.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<script src="{% static 'js/1.js' %}"></script>
	<link rel="stylesheet" href="{% static 'CSS/1.css' %}">
	<link rel="icon" href="{% static 'LOGO/img2.png' %}" type="image/x-icon">
	<title>Data Entry Portal</title>
</head>

<body class="animated_bg">
	<nav class="navbar nav nav-pills navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
		<div class="container-fluid">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar"> <span class="navbar-toggler-icon"></span> </button>
			<a class="navbar-brand mr-auto" href="{% url 'data_entry:main' %}"><img src="{% static 'Image/img.jpg' %}" height="40" width="41"></a>
			<div class="collapse navbar-collapse" id="Navbar">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:main' %}">Home</a></li>
					 {% if user.is_admin or user.is_staff %}
					<li class="nav-item"><a class="nav-link" href="{% url 'data_entry:view' %}">View Entry</a></li>
					{% endif %}
					<li class="nav-item"><a class="nav-link active" href="#">Data Entry</a></li>
				</ul>
			</div> <span class="navbar-text" id="logout">
				<a href="{% url 'login:logout' %}" ><span class="fa fa-sign-out"></span> Logout</a>
			</span>
		</div>
	</nav>
	<div class="container">
		<div class="row">
			<ol class="col-12 breadcrumb crumb">
				<li class="breadcrumb-item"><a href="#">Home</a></li>
				<li class="breadcrumb-item"><a href="#">View Entry</a></li>
				<li class="breadcrumb-item active">Data Entry</li>
			</ol>
		</div>
	</div>
	<br>
	<form method="post" action="{% url 'data_entry:entry' %}" enctype="multipart/form-data"> {% csrf_token %}
		<div class="container-lg">
			<div class="row row-content">
				<div class="col-12 offset-md-4 col-md-4">
					<h2>Registration Portal</h2> </div>
			</div>
			<div class="row row-conten">
				<div class="col-12 col-md-6">
					<label for="full_Name" class="col-md-2 col-form-label">Name:</label>
					<div class="col-md-8">
						<input type="text" placeholder="Please Enter Full Name" class="form-control" id="full_Name" name="full_Name" required pattern="^[A-Z][a-z ]{1,}[A-Z][a-z]{1,}"> </div>
				</div>
				<div class="col-12 offset-md-1 col-md-5">
					<label for="spouse_Name" class="col-md-5 col-form-label">Spouse Name:</label>
					<div class="col-md-10">
						<input type="text" placeholder="Please Enter Wife's Name" class="form-control" id="spouse_Name" name="spouse_Name" pattern="^[A-Z][a-z ]{1,}[A-Z][a-z]{6,}"> </div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-6">
					<label for="father_Name" class="col-md-4 col-form-label">Father's Name:</label>
					<div class="col-md-8">
						<input type="text" placeholder="Please Enter Father's Name" class="form-control" id="father_Name" required name="father_Name" pattern="^[A-Z][a-z ]{1,}[A-Z][a-z]{1,}"> </div>
				</div>
				<div class="col-12 offset-md-1 col-md-5">
					<label for="mother_Name" class="col-md-5 col-form-label">Mother's Name:</label>
					<div class="col-md-10">
						<input type="text" placeholder="Please Enter Mother's Name" class="form-control" id="mother_Name" required name="mother_Name" pattern="^[A-Z][a-z ]{1,}[A-Z][a-z]{1,}"> </div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-4 ">
					<label for="Occupation" class="col-md-3 col-form-label">Occupation:</label>
					<div class="col-md-12">
						<select id="Occupation" name="Occupation" class="form-control kem" required>
							<option value="Please Select occupation">Please Select occupation</option>
							<option value="Healthcare and medicine">Healthcare and medicine</option>
							<option value="Arts and entertainment">Arts and entertainment</option>
							<option value="Business">Business</option>
							<option value="Industrial and manufacturing">Industrial and manufacturing</option>
							<option value="Engineer">Engineer</option>
							<option value="Law enforcement and armed forces">Law enforcement and armed forces</option>
							<option value="Science and technology">Science and technology</option>
							<option value="Transport">Transport</option>
							<option value="Transport">Service(Labour)</option>
						</select>
					</div>
				</div>
				<div class="col-12 offset-md-1 col-md-2">
					<label for="Gender" class="col-md-3 col-form-label">Gender:</label>
					<div class="col-md-12">
						<input id="Gender" type="radio" required name="Gender" value="Male">
						<label class="form-check-label" for="Gender">Male</label>
						<input id="Genderf" type="radio" name="Gender" value="Female">
						<label class="form-check-label" for="Gender">Female</label>
					</div>
				</div>
				<div class="col-12 col-md-5">
					<label for="blood_Group" class="col-md-6 col-form-label">Blood Group:</label>
					<div class="col-md-10">
						<select id="blood_Group" name="blood_Group" class="form-control kem" required>
							<option value="Please Select Blood Group">Please Select Blood Group</option>
							<option value="O+">O+</option>
							<option value="O-">O-</option>
							<option value="A+">A+</option>
							<option value="O+">A-</option>
							<option value="B+">B+</option>
							<option value="B-">B-</option>
							<option value="AB+">AB+</option>
							<option value="AB-">AB-</option>
							<option value="Not Known">Not Known</option>
						</select>
					</div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-6">
					<label for="birth_date" class="col-md-5 col-form-label">Date of Birth(D.O.B):</label>
					<div class="col-md-8">
						<input id="birth_date" type="date" required name="birth_date" class="form-control kem"> </div>
				</div>
				<div class="col-12 offset-md-1 col-md-5">
					<label for="phone" class="col-md-5 col-form-label">Phone Number: </label>
					<div class="col-md-10">
						<input type="text" placeholder="Please Enter Phone Number" required id="phone" name="phone" pattern="[+][0-9]{12}" class="form-control" maxlength=13> </div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-6">
					<label for="Darbar" class="col-md-4 col-form-label">Darbar:</label>
					<div class="col-md-8">
						<select id="Darbar" name="Darbar" class="form-control kem" required>
							<option value="Please Select Darbar">Please Select Darbar</option>
							{% for darbar in darbars %}
							<option value="{{ darbar.darbar_name }}">{{ darbar.darbar_name }}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<div class="col-12 offset-md-1 col-md-5">
					<label for="Address" class="col-md-4 col-form-label">Address:</label>
					<div class="col-md-10">
						<input type="text" required placeholder="Please Enter Address" id="Address" name="Address" class="form-control"> </div>
				</div>
			</div>
			<div class="row row-content">
				<div class="col-12 col-md-6">
					<label for="Pincode" class="col-md-4 col-form-label">Pincode</label>
					<div class="col-md-8">
						<input type="text" required placeholder="Please Enter Pincode" id="Pincode" name="Pincode" pattern="[0-9]{6}" maxlength=6 class="form-control"> </div>
				</div>
				<div class="col-12 offset-md-1 col-md-5">
					<label for="myfile" class="col-md-4 col-form-label">Image:</label>
					<input type="file" id="myfile" name="myfile" class="form-control" required>or <a  onclick="window.open('{% url 'data_entry:camera' %}', 'newwindow','width=1390,height=670');"><i class="fa fa-camera" aria-hidden="true"></i></a></div>
			</div>
			<div class="row row-content">
				<div class="col-6 offset-md-1 col-md-7">
					<div class="col-1 offset-md-11 col-md-">
						<input type="submit" class="btn btn-btn btn-primary" value="Post"> </div>
				</div>
				<div class="col-5 offset-md-1 col-md-1">
					<div class="col-5 col-md-">
						<input type="reset" class="btn btn-btn btn-primary"> </div>
				</div>
			</div>
		</div>
	</form>
	<footer class="container-fluid bg-dark mt-5">
		<div class="card-lg bg-dark w-150">
			<div class="card-body">
				<!-- Copyright -->
				<div class="footer-copyright text-center" id="footer">© 2020 Copyright: <a href="https://ssdndeepu.com.com/"> SSDNDEEPU</a>
					<br>All Rights Reserved
					<br>
					<p> By using our site, you acknowledge that you have read and understand our <a href="TUS.html" target="_blank">Terms of Service.</a> </p>
				</div>
				<!-- Copyright -->
			</div>
		</div>
	</footer>
</body>
<script src="{% static 'js/main.js' %}"></script>
</html>

templates/data_entry/winner.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<title>Capture picture from your webcam</title>
	<style type="text/css">
		body { font-family: Helvetica, sans-serif; }
		h1 { margin:0 auto; text-align:center;}
		form { margin-top: 15px; }
		form > input { margin-right: 15px; }
		#results { margin:20px; padding:20px; border:1px solid; background:#ccc; }
	</style>
</head>
<body>
	<h1 class="text-uppercase">Shri Capture</h1>

	<div id="my_camera">
		<video autoplay="true" id="video" width="650" height="490"></video>&nbsp;
		<canvas id="canvas" width="650" height="490" ></canvas>
	</div>
		<br>
		<div class="row"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<div class="col-12 offset-md-9 col-md-1">
			<button class="btn btn-success" id="capture">CAPTURE</button></div>&nbsp;
		<div class="col-12 col-md-1">
			<input type="button" class="btn btn-btn btn-primary" class="left" value="Ok" id="do" onclick="myFunction()"> </div>
		</div>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>